<a href="/backers" class="mb-10 flex justify-center text-center" style="bottom:30px;position:relative">
  <div>
    <div class="h4 font-headlinecrack mb-2 text-primary-900">supported by</div>
    <div class="center">
     <img
       src="/images/logo-smol/logo-smol-colony-tackle.jpg"
       alt="logo-smol-colony-tackle.jpg"
       style="width:100px;"
       class="inline-flex"
     />
    </div>
    <div class="center">
      <img
        src="/images/logo-smol/logo-smol-duniaauto.jpg"
        alt="logo-smol-duniaauto.jpg"
        style="width:50px;"
        class="inline-flex"
      />
      <img
        src="/images/logo-smol/logo-smol-halim-sakti.jpg"
        alt="logo-smol-halim-sakti.jpg"
        style="width:50px;"
        class="inline-flex"
      />
      <img
        src="/images/logo-smol/logo-smol-uma-sukalila.jpg"
        alt="logo-uma-sukalila.jpg"
        style="width:50px;"
        class="inline-flex"
      />
      <img
        src="/images/logo-smol/logo-smol-seknet.jpg"
        alt="logo-seknet.jpg"
        style="width:50px;"
        class="inline-flex"
      />
      <img
        src="/images/logo-smol/logo-smol-locahouse.jpg"
        alt="logo-smol-locahouse.jpg"
        style="width:50px;"
        class="inline-flex"
      />
      <img
        src="/images/logo-smol/logo-smol-dl.jpg"
        alt="logo-smol-dl.jpg"
        style="width:50px;"
        class="inline-flex"
      />
    </div>
  </div>
</a>